import type { SplitMode, ShareInput, Category } from './money';
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Expense = {
  id: string;
  home_id: string;
  title: string;
  amount: number;
  currency: string;
  expense_date: string;
  payer: string;
  payer_name: string;
  category: Category;
  split_mode: SplitMode;
  version: number;
  created_by: string;
  created_by_name: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};
export type ExpenseSplit = {
  home_id: string;
  expense_id: string;
  user_id: string;
  user_name: string;
  amount: number;
  weight: number;
};
export type ExpenseBody = {
  title: string;
  amount: string;
  date: string;
  payer: string;
  category: Category;
  split_mode: SplitMode;
  participants: ShareInput[];
  shopping_list_id?: string;
};
export type Balance = { user_id: string; name: string; balance: string; active: boolean };
export type Settlement = {
  id: string;
  home_id: string;
  from_user: string;
  to_user: string;
  from_name: string;
  to_name: string;
  amount: number;
  currency: string;
  payment_date: string;
  created_by: string;
  created_by_name: string;
  created_at: string;
};
export type Recurring = {
  id: string;
  home_id: string;
  template: ExpenseBody;
  kind: 'fixed' | 'variable';
  frequency: 'weekly' | 'monthly';
  every_n: number;
  anchor_date: string;
  next_date: string;
  next_index: number;
  active: boolean;
  version: number;
  created_by: string;
  created_at: string;
  updated_at: string;
};
export type Occurrence = {
  id: string;
  home_id: string;
  recurring_id: string;
  period_date: string;
  template: ExpenseBody;
  recurrence_kind: 'fixed' | 'variable';
  status: 'pending' | 'posted';
  expense_id: string | null;
  created_at: string;
  updated_at: string;
};
export type Receipt = {
  id: string;
  home_id: string;
  expense_id: string;
  path: string;
  mime: string;
  size: number;
  created_at: string;
};
