export type Resource = {
  id: string;
  home_id: string;
  name: string;
  description: string;
  active: boolean;
  seed_key: string | null;
  version: number;
  created_by: string;
  created_by_name: string;
  created_at: string;
  updated_at: string;
};
export type Reservation = {
  id: string;
  home_id: string;
  resource_id: string;
  resource_name: string;
  title: string;
  responsible_id: string;
  responsible_name: string;
  starts_at: string;
  ends_at: string;
  created_by: string;
  created_by_name: string;
  created_at: string;
  updated_at: string;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  version: number;
  create_request: import('@/features/expenses/models').Json;
};
export type Activity = {
  id: string;
  home_id: string;
  title: string;
  description: string;
  location: string;
  starts_at: string;
  ends_at: string | null;
  created_by: string;
  created_by_name: string;
  created_at: string;
  updated_at: string;
  cancelled_at: string | null;
  version: number;
  create_request: import('@/features/expenses/models').Json;
};
export type ActivityMember = {
  home_id: string;
  activity_id: string;
  user_id: string;
  user_name: string;
  attending: boolean;
  joined_at: string;
  updated_at: string;
};
export type EventSource = 'tasks' | 'reservations' | 'activities' | 'expenses';
export type CalendarEvent = {
  id: string;
  sourceType: EventSource;
  sourceId: string;
  title: string;
  startsAt: string;
  endsAt: string | null;
  allDay: boolean;
  status: 'pending' | 'completed' | 'overdue' | 'scheduled';
  people: string[];
  names: string[];
  location?: string;
  href: string;
};
